###
GET http://localhost:3000/subscribers


###
GET http://localhost:3000/subscribers/60a67d26b23cb3b0984e88c1

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Attah",
    "subscribedToChannel": "Oyincode"
}

###
PATCH http://localhost:3000/subscribers/60a67d26b23cb3b0984e88c1
Content-Type: application/json

{
    "subscribedToChannel": "Nodes"
}